- exports.ctmpl
@fromonesrc this is needed before the other PR in infra for docs can go in. 
https://github.com/articulate/infra/pull/700#issuecomment-219727896
> read non secrets from consul

- entrypoint.sh
cc @articulate/web-ops 
pairing with @tecnobrat and @michaelcurran
> remove the ssl skipping

- exports.ctmpl
update secret/global/env_vars path in exports.ctmpl
> update secret/global/env_vars path in exports.ctmpl

- exports.ctmpl
add env_vars path to exports.ctmpl file
> add env_vars path to exports.ctmpl file

- entrypoint.sh
- install.sh
Should leave EB flows untouched in the case that an .app.json file does not exist.
> Use KMS for vault token if .app.json is present

- entrypoint.sh
Make this less :scream: and more :relaxed:
> Wording tweak

- entrypoint.sh
> use an env var for kms encrypted token

- exports.ctmpl
- install.sh
Requires APP_ENV _not_ be set as a global var at: `global/stage/env_vars/APP_ENV`
> Peer env as Stage

- export-vault.ctmpl
/cc @tecnobrat 
see: https://articulate.slack.com/archives/C0HU1TV6Y/p1509632899000556?thread_ts=1509573453.000084&cid=C0HU1TV6Y
> Don't fetch secrets from new style paths when APP_ENV=dev

- entrypoint.sh
- spec/Dockerfile_spec.rb
Peer passes in its entire env name, so we need to parse out just the first part.
> Peer passes more than just `peer`

- README.md
- install.sh
- spec/Dockerfile_spec.rb
- spec/dockerfiles/Dockerfile.debian.erb
Goals for refactor:
* shrink end container size by cleaning up cache after each step
* move to recommended way of installing aws cli
* move to software packages that are security compliant and supported (eg: python3)
* write some additional tests that make future changes more reliable
> Refactor install

- entrypoint.sh
In the kubernetes world, everything using this entrypoint script should have
a token, and if it failed to get one from vault, should crash and respawn.
This retries for 30 seconds, once every 3 seconds.
The original behaviour is retained for non-kubernetes applications.
> Retry getting a vault token instead of proceeding regardless

- Dockerfile
Ruby 2.4 will be end of life at the end of March https://www.ruby-lang.org/en/downloads/branches/.
> Upgrade to Ruby 2.5

- apiary/export-vault.ctmpl
- spec/Dockerfile_spec.rb
We do not want dev vars pulled into apiary envs.
> Remove dev vars from apiary env

- dev/export-consul.ctmpl
- dev/export-vault.ctmpl
- install.sh
- prod/export-consul.ctmpl
- prod/export-vault.ctmpl
- spec/Dockerfile_spec.rb
- stage/export-consul.ctmpl
- stage/export-vault.ctmpl
Notion: https://www.notion.so/9a463a3f03ed44f9b85408d30e5c88a9
> feat(export): writes path deprection log only when LOG_CONSUL_DEPRECATION=true

- scripts/docker-secrets
Add a script to make it easy to load Docker secrets as environment variables
> feat(scripts): add docker-secrets script

- scripts/awscli.sh
- [ticket](https://www.notion.so/awscli-51e5e58088eb4d06bbbfbfad45533d60)
> build(scripts): updates awscli to version 2.11.15

- go.mod
https://github.com/articulate/platform/issues/146
> build(go): upgrade to 1.22

- .golangci.yml
- go.mod
https://github.com/articulate/devex-sre/issues/338
> feat(golang): bumps to version 1.23.x

- .github/workflows/test.yaml
- .golangci.yaml
- .pre-commit-config.yaml
- main.go
- utils.go
- utils_test.go
> feat: upgrade golangci-lint to v2

- .golangci.yaml
- Makefile
- config_test.go
- consul_test.go
- utils_test.go
- validate.go
- validate_test.go
- vault.go
- vault_test.go
Add tests for config, consul, and vault.
Add more tests cases for validate
> test: add more tests
