articulate/docker-bootstrap

entrypoint.sh
exports.sh is being placed in the working dir `/app` but the source command is not telling the script where to find it currently. needs to use a full path.
=> place the exports.sh somewhere specific and source

entrypoint.sh
- the env variables are not getting passed to the exec command (I think) so run the source and the CMD in the same line
=> source the env variables at run the CMD

entrypoint.sh
testing it locally seems to work the old way.
=> put the exec back the way it was.

entrypoint.sh
- +x replaces an empty string with x if the variable exists but is empty. we do not want this to execute if the variable is empty.
=> fix the token check

entrypoint.sh
This way we don't have apps in a broken state, also spewing application startup failures to the logs.  But we still log something nice in logstash.
=> Don't proceed on an error and show a message

entrypoint.sh
From the docs:
```
| `max-stale`       | The maximum staleness of a query. If specified, Consul will distribute work among all servers instead of just the leader. The default value is 1s.
```
=> Request data from the leader always

entrypoint.sh
Currently there is an issue locally where it tried to load these up.
We always set these ADDRs in non-dev environments.
=> No consul / vault unless addrs are provided

install.sh
adding the wget apt-get package to the install.sh script because I'm getting some errors when trying to use this with my datadog-tracer-agent image.  getting the following error there during the build of that image using this install.sh script:
```
Cloning into 'docker-consul-template-bootstrap'...
/tmp/consul_template_install.sh: line 8: wget: command not found
unzip:  cannot find or open consul-template_0.18.0-rc1_linux_amd64.zip, consul-template_0.18.0-rc1_linux_amd64.zip.zip or consul-template_0.18.0-rc1_linux_amd64.zip.ZIP.
/tmp/consul_template_install.sh: line 11: wget: command not found
unzip:  cannot find or open awscli-bundle.zip, awscli-bundle.zip.zip or awscli-bundle.zip.ZIP.
sudo: ./awscli-bundle/install: command not found
```
=> add the wget apt-get package to install.sh script

entrypoint.sh
So that we don't have them in /tmp
=> Cleanup creds off disk.

export-consul.ctmpl, export-vault.ctmpl
Updating the consul-templates for the consul and vault environment variable setting to ignore setting environment variables that are already set via the ECS peer cluster if `APP_ENV` = peer.  This works via the `{{if and (scratch.Get "peer") (not (env .Key))}}` lines in the export-consul.ctmpl template and the `{{if and (scratch.Get "peer") (not (env .))}}` lines in the export-vault.ctmpl template.  They are both checking to see if the environment is peer and if the environment variable exists there.  I've tested this a bunch of times over already via an instance in the dev-zone that has access to consul and vault stage and it works great.
=> update consul templates to skip env vars set in peer already

export-consul.ctmpl, export-vault.ctmpl
similar to environment variables passed to the peer containers via `service.json` this will allow for local dev environment variables to be set via the docker-compose.yml that will override the consul/vault values from the `/dev` namespaces there.  this will make local tinkering with dev environments more flexible to one off changes/experimentation.
=> override consul and vault env vars for dev APP_ENV

entrypoint.sh
moving the `ENCRYPTED_VAULT_TOKEN` conditional in entrypoint.sh after the consul env var sourcing so we can stick the encrypted vault token in consul
=> move ENCRYPTED_VAULT_TOKEN conditional in entrypoint.sh

export-consul.ctmpl, export-vault.ctmpl
We are going to start reading environment variables from the namespace `products/${product_name}/env_vars` namespace.
This also adds support for dropping the environment name inside the consul / vault paths.
And thanks to @defn we have a much better conditional to detect if we should be exporting variables.
=> Add products namespace to consul/vault

export-consul.ctmpl, export-vault.ctmpl
rearranging env var order in consul and vault templates so that the order of precedence on sourcing them is:
1. App Level Env Vars (New Style trumps Old Style)
2. Product Level Env Vars
3. Global Level Env Vars (New Style trumps Old Style)
=> rearrange env var order in consul and vault templates

dev/export-vault.ctmpl, spec/Dockerfile_spec.rb
This needs to be fixed in some other way for using this for the dev namespace.  But this is how it worked prior to my refactor, so I'm just putting it back.
=> Dev doesn't currently load from new namespaces

peer/export-vault.ctmpl
pretty sure that this extra `(scratch.Get "env")` is messing with how the old app style secrets are being pulled from vault for peer - we're seeing global level vault env vars making it to containers but not older app level ones and I think this is why
=> remove Scratch.get from peer/export-vault.ctmpl

README.md, spec/Dockerfile_spec.rb
These tests should fail on the "head" branch, but pass on the "merge"
=> Add test for old vars, which should fail

Gemfile.lock, docker-compose.yml, entrypoint.sh, install.sh
This allows us to not require vault tokens at all for k8s services. Instead, we get the vault token via vault + k8s's auth integration.
=> Get vault token from k8s auth

dev/export-vault.ctmpl
adding the `SERVICE_PRODUCTS` level vault env vars to the dev export-vault consul-template so local dev can get access to some env vars in the products/dev vault namespace; the vault policy to all the dev policy to this namespace has been added already as well - https://github.com/articulate/vault-policies/pull/104
=> add products vault env vars to dev consul-template

entrypoint.sh
Getting some messages in an ECS Fargate Cron task that showed it was trying to authenticate to vault locally on port 8200 because it didn't pass in a `VAULT_TOKEN` env var and had the `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` env var associated with it because it was using a task role.  I'm thinking we should only be trying to connect to vault when the `VAULT_ADDR` is set in all cases.  Skipping all the vault bootstrap steps if that `VAULT_ADDR` env var isn't set to begin with.
=> skip all vault bootstrap steps if VAULT_ADDR isnt set

entrypoint.sh
In some cases, using k8s, we need to hardcode a token.
=> If a token is passed in, use that instead of querying kubernetes

install.sh, spec/dockerfiles/Dockerfile.alpine.erb
- When we use these scripts, we often call them with bash, so the shebang is not used
and thus -e is not used either.  Now we set our error options explicitly so that the
script will fail when something goes wrong
- Fixes missing py3-pip on Alpine https://medium.com/@ssorcnafets/apk-add-python3-py3-pip-c3f91cd3d1e1
causing awscli not to be installed
- Checks that expected packages are installed and found on the path
- Upgrades packages to latest versions
=> Use more defensive programming for install script

install.sh
At least on Debian Jesse (which is what FROM golang:1.6 uses),
there is no --no-cache-dir option anymore for pip3.
=> pip3 --no-cache-dir option is not available on apt-get variants

install.sh, spec/Dockerfile_spec.rb, spec/dockerfiles/Dockerfile.amazon-linux.erb
These images are interesting in that they don't have sudo on them.
Fortunately, none of the things we're using sudo for actually require it.
In other good news, these lambda images allow us to install jq from the amazon repository
rather than needing to use EPEL.
This also updates the vault binary location to match the other binaries being
installed.
Also adds tests for the amazon linux lambda nodejs image.
=> Add compatibility for amazon linux lambda images

entrypoint.sh, install.sh
When vault fails to get a token, it's not clear why.  Let's print the error message vault sent back if there's an error.
=> Display the vault error on failure to get a token

install.sh, prod/export-consul.ctmpl, prod/export-vault.ctmpl
https://github.com/articulate/docker-consul-template-bootstrap/pull/53 was originally done for staging,
but was never rolled out to prod.  This has led to occasional different behaviour with staging and prod
on the odd occasion that an env var was set both on the container and in consul to different values.
=> Make consul only be overrides in prod

.github/workflows/test.yml, install.sh
* Install the correct architecture binaries for consul-template and vault.
* Install the latest versions of those as of this PR.
* Use curl for any downloads so we don't need both curl and wget installed. (kept wget for now since other images are probably relying on it)
* Only install needed files from the bootstrap
* Make sure we are cleaning up bootstrap files we don't use
* Improve yum cleanup
=> improve install script

.github/workflows/test.yml, dev/export-consul.ctmpl, dev/export-vault.ctmpl, entrypoint.sh, install.sh, peer/export-consul.ctmpl, peer/export-vault.ctmpl, prod/export-consul.ctmpl, prod/export-vault.ctmpl, stage/export-consul.ctmpl, stage/export-vault.ctmpl
Make sure our entrypoint is following best practices and passes shellcheck. Improve logging, making sure everything goes to STDERR is is prefixed with a level.
Make sure we're using bash everywhere and we're allowing the system to select which bash to use if it's in a non-standard location. Installs bash on Alpine, since it doesn't ship with it by default and we use bash specific syntax in the entrypoint.
Clearly document which paths are deprecated, including products, which is newly deprecated
=> Cleanup entrypoint

README.md, entrypoint.sh
Adds support for a VAULT_AUTH_ROLE environment variable which will authenticate with a VAULT_AUTH_PROVIDER (default aws) to allow for more generic authentication methods.
=> feat(entrypoint): allow authenticating vault with a role

main.go
If no command is passed, it currently panics because it's trying to access an arg that wasn't passed
=> validate command is given

main.go
There have been a few cases where it would be nice to load additional paths, such as sharing env vars between a set of common applications. Adds the ability to set CONSUL_PATH and VAULT_PATH to load these additional paths (seperated by comma) after the default paths
=> allow loading of additional paths

entrypoint.sh, install.sh
There's a lot of debate about where or not `-o` as an `||` operative actually works.
I'm currently encountering an issue (documented in Slack [here](https://articulate.slack.com/archives/C01BSR9859A/p1668137365151549?thread_ts=1668028855.721709&cid=C01BSR9859A)) where this section of code isn't triggering, even when there is no VAULT_TOKEN, there is a AWS_CONTAINER_CREDENTIALS_RELATIVE_URI, and there is a VAULT_ROLE. I think it's because this messy `-o` logic isn't working. 
Splitting it in to two conditionals has the same outcome, it's just annoying duplicate code.
=> Simplify conditional statement

consul.go, consul_test.go
Using the DefaultConfig from consul and set the Address value, which Consul will then take care of parsing
=> fix(consul): don't parse address

main.go, vault.go
When running tests on Docker images, we won't be able to authenticate with Vault. Only authenticate Vault on known environments (ECS/Beanstalk and Lambda)
=> fix(vault): only authenticate vault in known AWS environment

main.go
PWD is set by shell, but since we aren't running via a shell, this value isn't being set. Use go to determine this path and set it.
=> fix: set PWD

config.go, config_test.go
When this was coverted to go, we accidentally made it load all secrets from global and products, but we originally intended it so that we never load secrets from stage into local dev due to the possibility of breaking stage.
Instead we only load secrets from a `dev` namespace to ensure that they don't collide.
See original code here: https://github.com/articulate/docker-consul-template-bootstrap/blob/11f43c1ad920a517b071d8d6ffc85876682065b5/dev/export-vault.ctmpl#L15-L29
=> Fix dev namespace for global and product lookups

consul.go
Sometimes it was picking up the top level as a keypair and causing an empty key to be inserted into the environment. Check the keypair has a value before adding it to the environment
=> fix(consul): skip empty consul keys

config.go, main.go, vault.go
We have a few processes that assume AWS_REGION is set. This was set in the previous version if not already set
=> feat: add AWS_REGION to default env vars

.github/workflows/test.yml, scripts/awscli.sh
Adds a script to install awscli@v2 while keeping the smallest layer size. Any tools it needs to install are then removed, but only if this script installed them
=> chore(scripts): add script to install awscli on Debian

env.go, env_test.go
There have been some vars added that have empty keys. Filter these out as it does cause some issues with tools like bundler
=> feat: remove env vars with empty keys

scripts/docker-secrets
If secrets do not exist, this will fail saying it cannot export *. Check for the directory first before trying to load secrets
=> fix(docker-secrets): allow secrets to run when there are no secrets

README.md, config.go, config_test.go, go.mod
Loads `service/{service}/{env}/env_var` path.
Change load order for env specific paths to take precedence.
Update to Go 1.20
=> feat: load service env paths

config.go, config_test.go, main.go
These have been deprecated for a while and we've finally been able to move everything over to either services or global instead
BREAKING CHANGE: removes loading from deprecated paths
=> feat!: don't load products and apps paths

scripts/awscli.sh
We have a rootless image we want to install awscli on, which requires setting bin-dir and a couple other options.
=> feat(scripts): run awscli install with passed arguments

.golangci.yml, Makefile, README.md, go.mod, go.sum, main.go
If environment is not set, it will try to load weird paths, which might not exist in Vault, so set this to a default with least privileges.
* Make sure SERVICE_NAME is set as a lot of paths need that to work
* Remove peer references as that's no longer a think
* Rename package to docker-bootstrap to match repo name
* Update to go 1.21
BREAKING CHANGE: will exit if SERVICE_NAME is not set
=> feat!: if SERVICE_ENV is not set, default to dev

config.go, config_test.go, main.go
There's a lot of services that don't define any of these inputs locally and are causing a bunch of issues. Remove the service name requirement and don't load those paths if there is no service.
=> fix: remove service name requirement

main.go
If service name is not set, it will not load service paths, does this quietly. Add a log message to call out that's what's happening
=> feat: log when SERVICE_NAME is not set

README.md
Fixing the `services/${SERVICE_NAME}/${SERVICE_ENV}` Consul and Vault paths to **/services**, it was previously set to `/service`. I double-checked the source code, and it expects the plural version of the word in both cases.
I also fixed a small typo in the example where a vault secret is set.
=> docs(README): Fix typo in vault and consul service paths

scripts/awscli.sh
Upgrading aws cli to the most recent version 2.15.25
=> chore(upgrade-aws-cli): upgrade aws cli to 2.15.25

config.go, go.mod, go.sum, logger.go, logger_test.go, main.go, utils.go, utils_test.go
Go now includes a nice way to do structured logs, including JSON. Use that instead of a third party module.
BREAKING CHANGE: log format will change a little bit
=> refactor(logging)!: switch to slog for logging

README.md, config.go, env.go, main.go, validate.go, validate_test.go
Allow parsing a service.json file for a list of required and optional variables. Log out any variables that aren't set for the given environment. If at least one required one is missing it will return an error
=> feat: validate environment variables

.github/CODEOWNERS, main.go
Applications are expecting to get SIGTERM to handle any shutdown. This currently doesn't forward signals and will just terminate the child process.
=> fix: forward signals to child process

main.go
We need to skip setting the process group id if we're starting a shell otherwise it just hangs
=> fix: allow starting shell

main.go
When running this directly without this option, some signals get sent twice. However, this is usually ran through Docker so it won't get duplicate signals. There are a lot of programs that are having issues with the group pid being set, so completely remove it
=> fix: remove set group pid

main.go
The process running PID 1 (which this is intended to be) has some additional responsibilities. First it needs to send signals, which was handled recently, but this improves upon. Secondly it needs to reap zombie processes, which is added here.
This now handles all signals and not just a subset of signals.
We found some issues while running yarn while setting pgid, so that's also not being set along with running shells. Warn on yarn usage since it could cause unexpected issues.
=> feat: handle zombie processes

main.go
npm also doesn't foward signals and isn't recommended for running commands
=> feat: warn on npm as well

validate.go
When missing require env vars, the final error message doesn't include any indication of what's missing. We do log in another line the list, but has lead to confusion when debugging
=> fix(validate): include missing env vars in error message

config.go, main.go, validate.go, validate_test.go
Allow different dependencies in different products. Requires SERVICE_PRODUCT to be set.
To help determine where the log is coming from, add a program field to logs
=> feat(validate): add products field to dependencies

main.go
We're getting some weird waitid errors. Doing a little bit of digging, it looks like we maybe want Setsid instead of pgid. I tested this against yarn and we weren't seeing the issue with pgid, so I removed that from the exceptions
=> fix: start child in session

go.mod, go.sum, main.go
When running with interactive (-i), run the child process in the foreground. Otherwise create a session
=> feat: run child process in foreground on interactive

go.mod, go.sum, main.go
We've ran into a lot of issues trying to have this forward signals and reap child processes, everything that PID 1 needs to do. Instead of having this contain everything we need, use dumb-init or tini or something similar for PID 1 responsibilities.
Because we don't need to worry about all that, we can use exec to replace the process with our child process instead of spawning a child process, which we'd need to forward signals to
BREAKING CHANGE: won't reap child processes
=> refactor!: replace the current process instead of spawning a child process

main.go
We are missing some env vars that are set on the image
=> fix: include base env vars during exec

main.go
When calling exec, the first arg needs to be the name of the command you are running
=> fix: pass name to exec args

config.go
Invert the conditional lookup of certain vault paths to enable
c.Environment = "dr" to receive appropriate keys.
=> fix(dr): enable vault lookups for SERVICE_ENV=dr

.github/CODEOWNERS, .pre-commit-config.yaml, logger.go, utils_test.go
Upgrade per-commit versions to latest to catch new linter checks
=> style: fix lint issues with latest golangci-lint

scripts/awscli.sh
These tools are needed when using commands like help
=> build(awscli): install groff and less

.goreleaser.yaml
This is causing some issues with our process scanner, so remove it and use the unpacked binary
=> fix(goreleaser): disable upx
